(function(){'use strict';
const STORAGE_KEY='pi_cookie_consent';const CONSENT_VERSION='2026-08-29-v1';const COOKIE_NAME='pi_cookie_consent';const OPTIONAL_COOKIE_PREFIXES=['_ga','_gid','_gat','_ym_','yandexuid','amcuid'];let currentPreference=readPreference();let lastFocusedElement=null;
document.documentElement.dataset.cookieAnalytics=currentPreference?.analytics?'granted':'denied';
function readPreference(){try{const parsed=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(parsed&&parsed.version===CONSENT_VERSION&&parsed.necessary===true)return parsed}catch(_){}const match=document.cookie.match(new RegExp('(?:^|; )'+COOKIE_NAME+'=([^;]*)'));if(!match)return null;const decoded=decodeURIComponent(match[1]);if(!decoded.startsWith(CONSENT_VERSION+':'))return null;return{version:CONSENT_VERSION,necessary:true,analytics:decoded.endsWith(':1'),decidedAt:null}}
function writePreference(analytics){currentPreference={version:CONSENT_VERSION,necessary:true,analytics:Boolean(analytics),decidedAt:new Date().toISOString()};try{localStorage.setItem(STORAGE_KEY,JSON.stringify(currentPreference))}catch(_){}const encoded=encodeURIComponent(CONSENT_VERSION+':'+(currentPreference.analytics?'1':'0'));document.cookie=COOKIE_NAME+'='+encoded+'; Max-Age=31536000; Path=/; SameSite=Lax; Secure';document.documentElement.dataset.cookieAnalytics=currentPreference.analytics?'granted':'denied';if(!currentPreference.analytics)removeOptionalCookies();document.dispatchEvent(new CustomEvent('pi:consentchange',{detail:{...currentPreference}}))}
function removeOptionalCookies(){document.cookie.split(';').forEach((item)=>{const name=item.split('=')[0].trim();if(!OPTIONAL_COOKIE_PREFIXES.some((prefix)=>name.startsWith(prefix)))return;document.cookie=name+'=; Max-Age=0; Path=/; SameSite=Lax; Secure'})}
function createButton(label,modifier,action){const button=document.createElement('button');button.type='button';button.className='pi-cookie-button'+(modifier?' '+modifier:'');button.textContent=label;button.addEventListener('click',action);return button}
function buildInterface(){if(window.self!==window.top)return;const banner=document.createElement('aside');banner.className='pi-cookie-banner';banner.setAttribute('aria-label','Настройки cookies');banner.innerHTML='<div><p class="pi-cookie-banner__eyebrow">Ваш выбор</p><h2 class="pi-cookie-banner__title">Cookies — под вашим контролем</h2><p class="pi-cookie-banner__text">Мы используем необходимые cookies и локальное хранилище для входа, безопасности и сохранения настроек. Необязательную аналитику включаем только с вашего согласия.</p><div class="pi-cookie-links"><a href="/cookies-policy.html">Политика cookies</a><a href="/privacypolicy.html">Политика обработки данных</a></div></div><div class="pi-cookie-banner__actions"></div>';
const overlay=document.createElement('div');overlay.className='pi-cookie-overlay';overlay.hidden=true;overlay.innerHTML='<section class="pi-cookie-dialog" role="dialog" aria-modal="true" aria-labelledby="pi-cookie-dialog-title"><button class="pi-cookie-dialog__close" type="button" aria-label="Закрыть настройки">×</button><p class="pi-cookie-dialog__eyebrow">Центр конфиденциальности</p><h2 class="pi-cookie-dialog__title" id="pi-cookie-dialog-title">Настройте cookies</h2><p class="pi-cookie-dialog__intro">Обязательные технологии нужны для работы сервиса. Аналитические можно разрешить или запретить — основные функции останутся доступны.</p><div class="pi-cookie-categories"><article class="pi-cookie-category"><div><h3 class="pi-cookie-category__title">Необходимые <span class="pi-cookie-category__badge">Всегда включены</span></h3><p class="pi-cookie-category__text">Поддерживают безопасный вход, сессию, сохранение выбора cookies, черновиков и настроек интерфейса.</p></div><label class="pi-cookie-switch" aria-label="Необходимые cookies всегда включены"><input type="checkbox" checked disabled><span aria-hidden="true"></span></label></article><article class="pi-cookie-category"><div><h3 class="pi-cookie-category__title">Аналитические</h3><p class="pi-cookie-category__text">Помогают понять, какие страницы удобны, без рекламного профилирования. Сейчас внешний сервис аналитики не подключён.</p></div><label class="pi-cookie-switch" aria-label="Разрешить аналитические cookies"><input class="pi-cookie-analytics-toggle" type="checkbox"><span aria-hidden="true"></span></label></article></div><p class="pi-cookie-dialog__note">Если в будущем изменятся сервис аналитики или цели обработки, версия согласия будет обновлена и мы запросим выбор заново.</p><div class="pi-cookie-dialog__actions"></div><div class="pi-cookie-links"><a href="/cookies-policy.html">Подробнее о технологиях и сроках</a><a href="/privacypolicy.html">Политика обработки данных</a></div></section>';
const trigger=document.createElement('button');trigger.type='button';trigger.className='pi-cookie-trigger';trigger.textContent='Настройки cookies';trigger.setAttribute('aria-label','Изменить настройки cookies');trigger.title='Настройки cookies';trigger.hidden=true;
const bannerActions=banner.querySelector('.pi-cookie-banner__actions');const dialogActions=overlay.querySelector('.pi-cookie-dialog__actions');const analyticsToggle=overlay.querySelector('.pi-cookie-analytics-toggle');const closeButton=overlay.querySelector('.pi-cookie-dialog__close');const dialog=overlay.querySelector('.pi-cookie-dialog');
function showSettings(){lastFocusedElement=document.activeElement;analyticsToggle.checked=Boolean(currentPreference?.analytics);overlay.hidden=false;document.documentElement.style.overflow='hidden';closeButton.focus()}
function closeSettings(){overlay.hidden=true;document.documentElement.style.overflow='';if(lastFocusedElement&&typeof lastFocusedElement.focus==='function')lastFocusedElement.focus()}
function finish(analytics){writePreference(analytics);banner.hidden=true;trigger.hidden=false;closeSettings()}
bannerActions.append(createButton('Принять все','pi-cookie-button--primary',()=>finish(true)),createButton('Только необходимые','pi-cookie-button--necessary',()=>finish(false)),createButton('Настроить','',showSettings));dialogActions.append(createButton('Сохранить выбор','pi-cookie-button--primary',()=>finish(analyticsToggle.checked)),createButton('Только необходимые','pi-cookie-button--necessary',()=>finish(false)));
trigger.addEventListener('click',showSettings);closeButton.addEventListener('click',closeSettings);overlay.addEventListener('click',(event)=>{if(event.target===overlay)closeSettings()});overlay.addEventListener('keydown',(event)=>{if(event.key==='Escape'){closeSettings();return}if(event.key!=='Tab')return;const focusable=[...dialog.querySelectorAll('button:not([disabled]), input:not([disabled]), a[href]')];if(!focusable.length)return;const first=focusable[0];const last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}});
const footer=document.querySelector('.site-footer');document.body.append(banner,overlay);(footer||document.body).append(trigger);if(currentPreference){banner.hidden=true;trigger.hidden=false}else{banner.hidden=false;trigger.hidden=true}window.PIConsent={get:()=>currentPreference?{...currentPreference}:null,allows:(category)=>category==='necessary'||(category==='analytics'&&Boolean(currentPreference?.analytics)),open:showSettings};document.documentElement.dataset.cookieConsentReady='true';document.dispatchEvent(new CustomEvent('pi:consentready',{detail:window.PIConsent.get()}))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',buildInterface,{once:true});else buildInterface()})();
