(function(){
  'use strict';
  var root=document.getElementById('invitation'),slug=location.pathname.split('/').filter(Boolean).pop(),payload=null,lookbook={group:'women',index:0},months=['января','февраля','марта','апреля','мая','июня','июля','августа','сентября','октября','ноября','декабря'];
  var themeSlugs={'Священный сад':'sacred','Бархатный вечер':'velvet','Воздушный шёлк':'silk','Лунный сад':'moon','Русская усадьба':'estate','Современная клятва':'editorial'};
  function safe(v){return String(v==null?'':v).replace(/[&<>'"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]})}
  function data(){return payload.project&&payload.project.data||{}}
  function rich(key,fallback){var v=data().richFields&&data().richFields[key];return v==null||v===''?(fallback||''):v}
  function feature(key,defaultValue){var f=data().features;return f&&key in f?!!f[key]:!!defaultValue}
  function media(src,alt,cls){return src?'<img class="'+(cls||'')+'" src="'+safe(src)+'" alt="'+safe(alt)+'">':''}
  function dateParts(){var raw=data().date,date=raw?new Date(raw+'T12:00:00'):null;return date&&!isNaN(date)?{date:date,text:date.getDate()+' '+months[date.getMonth()]+' '+date.getFullYear()}:null}
  function section(kicker,body,classes){return '<section class="section '+(classes||'')+'"><span class="section-kicker">'+safe(kicker)+'</span>'+body+'</section>'}
  function normalizeUrl(value){try{var u=new URL(String(value||''));return /^https?:$/.test(u.protocol)?u.href:''}catch(e){return ''}}
  function telegramUrl(value){var raw=String(value||'').trim();if(!raw)return '';if(raw.charAt(0)==='@')raw=raw.slice(1);if(/^[a-zA-Z0-9_]{5,32}$/.test(raw))return 'https://t.me/'+raw;var url=normalizeUrl(raw);if(!url)return '';var host=new URL(url).hostname.toLowerCase().replace(/^www\./,'');return host==='t.me'||host==='telegram.me'?url:''}
  function whatsappUrl(value){var raw=String(value||'').trim();if(!raw)return '';var digits=raw.replace(/\D/g,'');if(/^\d{10,15}$/.test(digits))return 'https://wa.me/'+digits;var url=normalizeUrl(raw);if(!url)return '';var host=new URL(url).hostname.toLowerCase().replace(/^www\./,'');return host==='wa.me'||host==='api.whatsapp.com'||host==='chat.whatsapp.com'?url:''}
  function maxUrl(value){var url=normalizeUrl(value);if(!url)return '';var host=new URL(url).hostname.toLowerCase().replace(/^www\./,'');return host==='max.ru'||host.endsWith('.max.ru')?url:''}
  function updateMessengerField(form){var select=form.querySelector('[name="messenger"]'),input=form.querySelector('[name="contact"]'),label=form.querySelector('[data-contact-label]'),meta={telegram:['Контакт в Telegram *','@username, t.me/… или номер','text'],whatsapp:['Контакт в WhatsApp *','+7 999 000-00-00 или wa.me/…','tel'],max:['Контакт в MAX *','Ссылка max.ru/… или номер','text']},item=meta[select.value]||meta.telegram;label.textContent=item[0];input.placeholder=item[1];input.inputMode=item[2]}
  function galleryPhotos(){try{var list=JSON.parse(rich('galleryPhotos','[]'));return Array.isArray(list)?list.filter(Boolean):[]}catch(e){return []}}
  function countdownMarkup(){return section(rich('countdownCaption','ДО ТОРЖЕСТВА ОСТАЛОСЬ'),'<div class="countdown-grid" id="countdown"><span><b>—</b><em>дней</em></span><span><b>00</b><em>часов</em></span><span><b>00</b><em>минут</em></span><span><b>00</b><em>секунд</em></span></div>','countdown')}
  function musicMarkup(){var source=normalizeUrl(data().musicName);if(!source)return '';return '<section class="music-invitation"><audio id="invitation-music" preload="none" loop src="'+safe(source)+'"></audio><button type="button" id="music-toggle" aria-pressed="false"><span aria-hidden="true">▶</span><b>Включить музыку</b></button></section>'}
  function locationMarkup(){var map=normalizeUrl(rich('mapUrl')),photo=rich('venuePhoto'),link=map||(data().address?'https://yandex.ru/maps/?text='+encodeURIComponent(data().address):'');return section('ЛОКАЦИЯ','<p>Наш праздник пройдёт на площадке:</p><h2>'+safe(data().venue||'Место торжества')+'</h2><p class="location-address">'+safe(data().address||'Адрес будет указан позже')+'</p>'+media(photo,'Площадка','location-photo')+'<p>'+safe(rich('venueNote',rich('mapNote','Откройте маршрут в удобном навигаторе')))+'</p>'+(link?'<a class="action-link" href="'+safe(link)+'" target="_blank" rel="noopener">Открыть карту</a>':''),'location light')}
  function scheduleMarkup(){var items=(data().schedule||[]).filter(function(x){return x&&x[0]&&x[1]});if(!items.length)return '';return section('ПРОГРАММА ДНЯ','<div class="schedule-list">'+items.map(function(x){return '<div class="schedule-item"><b>'+safe(x[0])+'</b><span>'+safe(x[1])+'</span></div>'}).join('')+'</div>','schedule')}
  function storyMarkup(){if(!feature('story',true))return '';return section('НАША ИСТОРИЯ',media(rich('storyPhoto'),'Фотография пары','story-photo')+'<div class="story-copy"><p>'+safe(rich('storyText','Наша общая история только начинается'))+'</p></div>','story')}
  function lookbookMarkup(){if(!feature('dress',true))return '';var colors=[1,2,3,4,5].map(function(i){return '<i style="background:'+safe(rich('dressColor'+i,'#d8bd81'))+'"></i>'}).join('');return section('ДРЕСС-КОД','<p>'+safe(rich('dressText',data().dressText||'Будем рады нарядам из выбранной палитры'))+'</p><div class="palette">'+colors+'</div><div class="lookbook-tabs"><button class="is-active" data-look-group="women">Девушкам</button><button data-look-group="men">Мужчинам</button></div><div class="lookbook-stage"><img id="look-image" alt="Пример образа"><div class="carousel-nav"><button data-look-move="-1" aria-label="Предыдущий образ">‹</button><span id="look-counter">1 / 5</span><button data-look-move="1" aria-label="Следующий образ">›</button></div></div><p id="look-copy">'+safe(rich('dressWomen','Вечерние платья и костюмы'))+'</p>','dress')}
  function giftsMarkup(){if(!feature('gifts',false))return '';var gifts=Array.isArray(data().giftItems)?data().giftItems:[],reserved=new Set(payload.reservedGiftIds||[]);var cards=gifts.map(function(g){var taken=reserved.has(String(g.id));return '<article class="gift-card" data-gift-card="'+safe(g.id)+'">'+(g.image?media(g.image,g.title,''):'')+'<div class="card-copy"><h3>'+safe(g.title||'Подарок')+'</h3>'+(g.price?'<b>'+safe(g.price)+'</b>':'')+'<div class="card-actions">'+(normalizeUrl(g.url)?'<a href="'+safe(normalizeUrl(g.url))+'" target="_blank" rel="noopener">Открыть в магазине</a>':'')+'<button data-gift="'+safe(g.id)+'" data-title="'+safe(g.title||'Подарок')+'" '+(taken?'disabled':'')+'>'+(taken?'Уже забронирован':'Забронировать')+'</button></div></div></article>'}).join('');return section('НАШИ ПОЖЕЛАНИЯ','<p>'+safe(rich('giftsText','Главный подарок для нас — ваше присутствие'))+'</p>'+(cards?'<div class="cards-carousel">'+cards+'</div>':''),'gifts')}
  function simpleFeature(key,kicker,title,text,mark){if(key==='video')return videoMarkup();if(!feature(key,false))return '';return section(kicker,'<div class="feature-card">'+(mark?'<div class="format-mark">'+safe(mark)+'</div>':'')+(title?'<h2>'+safe(title)+'</h2>':'')+'<p>'+safe(text)+'</p></div>',key)}
  function transfersMarkup(){if(!feature('transfer',false))return '';var items=Array.isArray(data().transferRoutes)?data().transferRoutes:[];var cards=items.map(function(x){return '<article class="transfer-card">'+(x.photo?media(x.photo,'Ориентир','transfer-photo'):'')+'<div class="card-copy"><b>'+safe(x.time||'')+'</b><h3>'+safe(x.title||'Трансфер')+'</h3><p>'+safe([x.from,x.to].filter(Boolean).join(' → '))+'</p><div class="tags">'+[x.vehicle,x.seats&&x.seats+' мест',x.note].filter(Boolean).map(function(v){return '<span>'+safe(v)+'</span>'}).join('')+'</div>'+(x.phone?'<div class="card-actions"><a href="tel:'+safe(String(x.phone).replace(/[^+\d]/g,''))+'">Связаться с водителем</a></div>':'')+'</div></article>'}).join('');return cards?section('ТРАНСФЕР','<p>Выберите удобный маршрут</p><div class="cards-carousel">'+cards+'</div>','transfer'):''}
  function staysMarkup(){if(!feature('accommodation',false))return '';var items=Array.isArray(data().accommodationOptions)?data().accommodationOptions:[];var cards=items.map(function(x){var route=x.address?'https://yandex.ru/maps/?text='+encodeURIComponent(x.address):'';return '<article class="stay-card">'+(x.photo?media(x.photo,x.name,'stay-photo'):'')+'<div class="card-copy"><h3>'+safe(x.name||'Вариант проживания')+'</h3><p>'+safe(x.address||'')+'</p><div class="tags">'+[x.price,x.distance,x.checkin&&'Заезд '+x.checkin,x.checkout&&'Выезд '+x.checkout,x.promo&&'Промокод '+x.promo].filter(Boolean).map(function(v){return '<span>'+safe(v)+'</span>'}).join('')+'</div><p>'+safe(x.note||'')+'</p><div class="card-actions">'+(normalizeUrl(x.bookingUrl)?'<a href="'+safe(normalizeUrl(x.bookingUrl))+'" target="_blank" rel="noopener">Забронировать</a>':'')+(route?'<a href="'+safe(route)+'" target="_blank" rel="noopener">Маршрут</a>':'')+'</div></div></article>'}).join('');return cards?section('ГДЕ ОСТАНОВИТЬСЯ','<p>Подобрали варианты рядом с площадкой</p><div class="cards-carousel">'+cards+'</div>','accommodation light'):''}
  function galleryMarkup(){if(!feature('gallery',false))return '';var photos=galleryPhotos();return photos.length?section('НАШИ ФОТОГРАФИИ','<div class="gallery">'+photos.map(function(p,i){return media(p,'Фотография '+(i+1),'')}).join('')+'</div>','gallery-section light'):''}
  function childhoodMarkup(){if(!feature('childhood',false))return '';var one=rich('childOnePhoto'),two=rich('childTwoPhoto');if(!one&&!two)return '';return section('КАК ВСЁ НАЧИНАЛОСЬ','<div class="child-grid">'+media(one,'Детская фотография','child-photo')+media(two,'Детская фотография','child-photo')+'</div><p>'+safe(rich('childhoodText','Узнали нас?'))+'</p>','childhood')}
  function videoMarkup(){if(!feature('video',false))return '';var url=normalizeUrl(rich('videoUrl')||rich('videoFile')),poster=rich('videoPoster'),caption=rich('videoCaption','Посмотрите нашу историю');if(!url)return '';var direct=/\.(?:mp4|webm|ogg)(?:[?#].*)?$/i.test(url),content=direct?'<video class="story-video" controls playsinline preload="metadata" '+(poster?'poster="'+safe(poster)+'"':'')+'><source src="'+safe(url)+'"></video>':(poster?media(poster,caption,'video-poster'):'<div class="video-mark" aria-hidden="true">▶</div>')+'<a class="action-link" href="'+safe(url)+'" target="_blank" rel="noopener">Смотреть видео</a>';return section('НАШЕ ВИДЕО','<p>'+safe(caption)+'</p><div class="video-card">'+content+'</div>','video')}
  function faqMarkup(){if(!feature('faq',false))return '';var list=[[rich('faqQuestion1'),rich('faqAnswer1')],[rich('faqQuestion2'),rich('faqAnswer2')]];(data().customQuestions||[]).forEach(function(q){list.push([q,'Ответ организаторов появится здесь'])});list=list.filter(function(x){return x[0]});return section('ВОПРОСЫ И ОТВЕТЫ','<div class="faq-list">'+list.map(function(x){return '<details><summary>'+safe(x[0])+'</summary><p>'+safe(x[1])+'</p></details>'}).join('')+'</div>','faq')}
  function contactsMarkup(){if(!feature('contacts',true))return '';var phone=rich('contactPhone'),telegram=telegramUrl(rich('contactTelegram')),whatsapp=whatsappUrl(rich('contactWhatsapp')),max=maxUrl(rich('contactMax')),actions=(telegram?'<a href="'+safe(telegram)+'" target="_blank" rel="noopener">Написать в Telegram</a>':'')+(whatsapp?'<a href="'+safe(whatsapp)+'" target="_blank" rel="noopener">Написать в WhatsApp</a>':'')+(max?'<a href="'+safe(max)+'" target="_blank" rel="noopener">Написать в MAX</a>':'')+(phone?'<a href="tel:'+safe(phone.replace(/[^+\d]/g,''))+'">'+safe(phone)+'</a>':'');return section('КОНТАКТЫ',media(rich('contactPhoto'),rich('contactName','Координатор'),'contact-photo')+'<h2>'+safe(rich('contactName','Координатор'))+'</h2><p>'+safe(rich('contactText','В день торжества по всем вопросам можно обратиться к координатору'))+'</p><div class="contact-actions">'+actions+'</div>','contacts')}
  function rsvpMarkup(){var labels={count:'Количество гостей',companions:'Имена сопровождающих',meal:'Выбор меню',transfer:'Трансфер',children:'Дети',contact:'Контакт'},questions=Object.keys(data().rsvpQuestions||{}).filter(function(k){return k!=='dietary'&&data().rsvpQuestions[k]}).map(function(k){return labels[k]||k}),deadline=data().rsvpDeadline?new Date(data().rsvpDeadline+'T12:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long'}):'';return section('БУДЕТЕ ЛИ ВЫ С НАМИ?','<h2>Ответьте на приглашение</h2><p>Короткая анкета займёт около минуты'+(deadline?'. Ответьте до '+safe(deadline):'')+'.</p><div class="tags">'+['Имя и мессенджер'].concat(questions.slice(0,4)).map(function(x){return '<span>'+safe(x)+'</span>'}).join('')+'</div><button class="primary-action" id="open-rsvp">Ответить на приглашение</button>','rsvp')}
  function openingMarkup(theme,date){
    var labels={sacred:'Открыть приглашение',velvet:'Войти в вечер',silk:'Прикоснуться',moon:'Зажечь звёзды',estate:'Распечатать письмо',editorial:'Открыть выпуск'};
    var d=data();
    return '<div class="published-opening" id="opening" role="dialog" aria-modal="true" aria-labelledby="opening-title" data-theme="'+theme+'">'+
      '<div class="opening-scene" aria-hidden="true"><i class="opening-left"></i><i class="opening-right"></i><i class="opening-flap"></i><i class="opening-orbit"></i></div>'+
      '<div class="opening-card">'+(date?'<span class="opening-number">'+safe(date.text)+'</span>':'')+
      '<p class="opening-eyebrow">ПРИГЛАШЕНИЕ НА СВАДЬБУ</p><h2 id="opening-title"><span>'+safe(d.nameOne||'Ваше имя')+'</span><small>и</small><span>'+safe(d.nameTwo||'Имя партнёра')+'</span></h2>'+
      '<button type="button" id="opening-button">'+labels[theme]+'</button></div></div>';
  }
  function mountOpening(theme,date){
    var old=document.getElementById('opening');if(old)old.remove();
    root.insertAdjacentHTML('beforebegin',openingMarkup(theme,date));
    var opening=document.getElementById('opening'),button=document.getElementById('opening-button');
    var longNames=Math.max(String(data().nameOne||'').length,String(data().nameTwo||'').length)>15;
    opening.classList.toggle('long-names',longNames);
    root.querySelector('.cover h1').classList.toggle('long-names',longNames);
    root.inert=true;document.body.classList.add('opening-lock');button.focus({preventScroll:true});
    button.addEventListener('click',function(){
      if(opening.classList.contains('is-opening'))return;
      opening.classList.add('is-opening');button.disabled=true;
      var reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
      window.setTimeout(function(){
        opening.classList.add('is-gone');opening.setAttribute('aria-hidden','true');
        root.inert=false;document.body.classList.remove('opening-lock');
        root.querySelector('.cover h1').focus({preventScroll:true});
      },reduced?0:900);
    });
  }
  function render(){var d=data(),date=dateParts(),theme=themeSlugs[payload.theme]||themeSlugs[payload.project.template]||'sacred';root.dataset.theme=theme;document.documentElement.style.setProperty('--bg',d.color||'');document.querySelector('meta[name="theme-color"]').content=d.color||'#123f33';document.title=(d.nameOne&&d.nameTwo?d.nameOne+' и '+d.nameTwo:'Приглашение на свадьбу');var cover='<section class="section cover"><div class="monogram">'+safe((d.nameOne||'В').charAt(0).toUpperCase())+' · '+safe((d.nameTwo||'И').charAt(0).toUpperCase())+'</div><span class="section-kicker">ПРИГЛАШЕНИЕ НА СВАДЬБУ</span><h1 tabindex="-1"><span>'+safe(d.nameOne||'Ваше имя')+'</span><small>и</small><span>'+safe(d.nameTwo||'Имя партнёра')+'</span></h1><p class="cover-message">'+safe(d.message||'Будем счастливы разделить с вами этот особенный день')+'</p>'+(date?'<div class="date-card"><b>'+safe(date.text)+'</b><span>НАЧАЛО В '+safe(d.time||'16:00')+'</span></div>':'')+'<div class="scroll-cue"><span>ЛИСТАЙТЕ НИЖЕ</span><i>⌄</i></div></section>';var html=cover+(feature('countdown',true)&&date?countdownMarkup():'')+locationMarkup()+scheduleMarkup()+storyMarkup()+lookbookMarkup()+giftsMarkup()+simpleFeature('flowers','ЦВЕТЫ','',rich('flowersText','Пожелания по цветам'),'✿')+simpleFeature('format',rich('formatLabel','ВАЖНО ЗНАТЬ'),rich('formatTitle','Формат праздника'),rich('formatText','Важная информация для гостей'),({adults:'18+',family:'ВСЕ',teens:'12+',ask:'?'})[rich('formatType','adults')])+transfersMarkup()+staysMarkup()+simpleFeature('menu','МЕНЮ','',rich('menuText','Информация о праздничном ужине'),'♨')+simpleFeature('activities','АКТИВНОСТИ',rich('activitiesTitle','Чем займёмся вместе'),rich('activitiesText','Развлечения и активности'),'✦')+simpleFeature('prewedding','ДО СВАДЬБЫ',rich('preweddingTitle','Встреча до свадьбы'),[rich('preweddingDate'),rich('preweddingPlace'),rich('preweddingText')].filter(Boolean).join(' · '),'☆')+galleryMarkup()+childhoodMarkup()+simpleFeature('video','НАШЕ ВИДЕО','',rich('videoCaption','Наша история'),'▶')+faqMarkup()+contactsMarkup()+rsvpMarkup()+'<footer class="footer">ЖДЁМ ВАС</footer>';root.innerHTML=html;bind();updateCountdown();setInterval(updateCountdown,1000);renderLookbook();mountOpening(theme,date)}
  function updateCountdown(){var box=document.getElementById('countdown');if(!box)return;var target=new Date(data().date+'T'+(data().time||'00:00')+':00'),left=Math.max(0,target-Date.now()),seconds=Math.floor(left/1000),values=[Math.floor(seconds/86400),String(Math.floor(seconds%86400/3600)).padStart(2,'0'),String(Math.floor(seconds%3600/60)).padStart(2,'0'),String(seconds%60).padStart(2,'0')];Array.from(box.querySelectorAll('b')).forEach(function(el,i){el.textContent=values[i]})}
  function paletteKey(){return rich('dressPaletteKey','natural')}
  function renderLookbook(){var img=document.getElementById('look-image');if(!img)return;img.src='../../assets/dress-code/looks/'+paletteKey()+'/'+lookbook.group+'-'+(lookbook.index+1)+'.jpg';img.alt=(lookbook.group==='women'?'Женский':'Мужской')+' образ '+(lookbook.index+1);document.getElementById('look-counter').textContent=(lookbook.index+1)+' / 5';document.getElementById('look-copy').textContent=rich(lookbook.group==='women'?'dressWomen':'dressMen');document.querySelectorAll('[data-look-group]').forEach(function(b){b.classList.toggle('is-active',b.dataset.lookGroup===lookbook.group)})}
  function bind(){document.querySelectorAll('[data-look-group]').forEach(function(b){b.addEventListener('click',function(){lookbook.group=b.dataset.lookGroup;lookbook.index=0;renderLookbook()})});document.querySelectorAll('[data-look-move]').forEach(function(b){b.addEventListener('click',function(){lookbook.index=(lookbook.index+Number(b.dataset.lookMove)+5)%5;renderLookbook()})});document.querySelectorAll('[data-gift]').forEach(function(b){b.addEventListener('click',function(){var dialog=document.getElementById('gift-dialog');dialog.querySelector('[name="giftId"]').value=b.dataset.gift;document.getElementById('gift-dialog-title').textContent=b.dataset.title;dialog.showModal()})});var open=document.getElementById('open-rsvp');if(open)open.addEventListener('click',function(){document.getElementById('rsvp-dialog').showModal()})}
  function extraForm(){var q=data().rsvpQuestions||{},max=Math.max(1,Math.min(12,Number(data().rsvpConfig&&data().rsvpConfig.maxGuests)||4)),html='<div class="extra-grid">';if(q.count){html+='<label><span>Количество взрослых</span><select name="adultCount">';for(var i=1;i<=max;i++)html+='<option value="'+i+'">'+i+'</option>';html+='</select></label>'}if(q.companions)html+='<label><span>Имена сопровождающих</span><input name="companions" maxlength="300" placeholder="Всех, кроме себя"></label>';if(q.children)html+='<label><span>Дети: имена и возраст</span><input name="children" maxlength="300" placeholder="Если будут"></label>';if(q.meal){var meals=rich('menuOptions','Классическое, Вегетарианское, Детское').split(',').filter(Boolean);html+='<label><span>Предпочтение по меню</span><select name="meal">'+meals.map(function(m){return '<option>'+safe(m.trim())+'</option>'}).join('')+'</select></label><p class="health-data-note">Особые медицинские ограничения не указывайте здесь — сообщите организаторам лично.</p>'}if(q.transfer)html+='<label><span>Нужен трансфер?</span><select name="transfer"><option value="no">Нет</option><option value="yes">Да</option></select></label>';if((data().customQuestions||[]).length)(data().customQuestions||[]).forEach(function(text,i){html+='<label><span>'+safe(text)+'</span><input name="custom_'+i+'" maxlength="500"></label>'});return html+'</div>'}
  ['rsvp-form','gift-form'].forEach(function(id){var form=document.getElementById(id);updateMessengerField(form);form.querySelector('[name="messenger"]').addEventListener('change',function(){updateMessengerField(form)})});
  document.getElementById('rsvp-form').addEventListener('change',function(e){if(e.target.name==='status'){var extra=document.getElementById('rsvp-extra');extra.hidden=e.target.value!=='accepted';extra.innerHTML=e.target.value==='accepted'?extraForm():''}});
  async function post(url,body){var response=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),json=await response.json().catch(function(){return {}});if(!response.ok)throw new Error(json.error||'Не удалось отправить данные');return json}
  document.getElementById('rsvp-form').addEventListener('submit',async function(e){e.preventDefault();var form=e.currentTarget,error=document.getElementById('rsvp-error'),submit=form.querySelector('[type="submit"]'),fd=new FormData(form),answers={};fd.forEach(function(v,k){if(!['name','messenger','contact','status','personalDataAccepted'].includes(k))answers[k]=v});error.textContent='';submit.disabled=true;try{await post('/api/invitations/'+encodeURIComponent(slug)+'/rsvp',{name:fd.get('name'),messenger:fd.get('messenger'),contact:fd.get('contact'),status:fd.get('status'),answers:answers,personalDataAccepted:fd.get('personalDataAccepted')==='on'});form.closest('dialog').close();form.reset();updateMessengerField(form);document.getElementById('rsvp-extra').hidden=true;toast('Спасибо! Ответ отправлен организаторам')}catch(err){error.textContent=err.message}finally{submit.disabled=false}});
  document.getElementById('gift-form').addEventListener('submit',async function(e){e.preventDefault();var form=e.currentTarget,error=document.getElementById('gift-error'),submit=form.querySelector('[type="submit"]'),fd=new FormData(form),giftId=fd.get('giftId');error.textContent='';submit.disabled=true;try{await post('/api/invitations/'+encodeURIComponent(slug)+'/gifts/'+encodeURIComponent(giftId)+'/reserve',{name:fd.get('name'),messenger:fd.get('messenger'),contact:fd.get('contact'),personalDataAccepted:fd.get('personalDataAccepted')==='on'});var button=document.querySelector('[data-gift="'+CSS.escape(giftId)+'"]');if(button){button.disabled=true;button.textContent='Уже забронирован'}form.closest('dialog').close();form.reset();updateMessengerField(form);toast('Подарок забронирован за вами')}catch(err){error.textContent=err.message}finally{submit.disabled=false}});
  document.querySelectorAll('.dialog-close').forEach(function(button){button.addEventListener('click',function(){var dialog=button.closest('dialog');if(dialog)dialog.close()})});
  function attachMusic(){if(!payload||!normalizeUrl(data().musicName)||root.querySelector('.music-invitation'))return;var cover=root.querySelector('.cover');if(cover)cover.insertAdjacentHTML('afterend',musicMarkup())}
  new MutationObserver(attachMusic).observe(root,{childList:true});root.addEventListener('click',function(event){var toggle=event.target.closest('#music-toggle');if(!toggle)return;var music=document.getElementById('invitation-music');if(!music)return;if(music.paused){music.play().then(function(){toggle.classList.add('is-playing');toggle.setAttribute('aria-pressed','true');toggle.querySelector('span').textContent='Ⅱ';toggle.querySelector('b').textContent='Поставить на паузу'}).catch(function(){toast('Браузер не смог включить музыку. Попробуйте ещё раз.')})}else{music.pause();toggle.classList.remove('is-playing');toggle.setAttribute('aria-pressed','false');toggle.querySelector('span').textContent='▶';toggle.querySelector('b').textContent='Включить музыку'}})
  function toast(text){var el=document.getElementById('guest-toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(function(){el.classList.remove('show')},3500)}
  function loadInvitation(attempt){root.setAttribute('aria-busy','true');return fetch('/api/invitations/'+encodeURIComponent(slug),{headers:{accept:'application/json'}}).then(function(r){if(r.ok)return r.json();var error=new Error(r.status===404?'not-found':'temporary');error.kind=r.status===404?'not-found':'temporary';throw error}).catch(function(error){if(error.kind!=='not-found'&&attempt<2)return new Promise(function(resolve){setTimeout(resolve,700*(attempt+1))}).then(function(){return loadInvitation(attempt+1)});throw error})}
  loadInvitation(0).then(function(json){payload=json;root.removeAttribute('aria-busy');render()}).catch(function(error){root.removeAttribute('aria-busy');var missing=error.kind==='not-found';root.innerHTML='<div class="error-page"><h1>'+(missing?'Приглашение не найдено':'Не удалось открыть приглашение')+'</h1><p>'+(missing?'Проверьте ссылку или попросите организаторов отправить её ещё раз.':'Соединение временно недоступно. Обновите страницу — ваши данные не потеряются.')+'</p><button type="button" id="retry-invitation">'+(missing?'На главную':'Попробовать ещё раз')+'</button></div>';var retry=document.getElementById('retry-invitation');if(retry)retry.addEventListener('click',function(){if(missing)location.href='/';else{root.innerHTML='<div class="invitation-loading"><i></i><p>Открываем приглашение…</p></div>';loadInvitation(0).then(function(json){payload=json;root.removeAttribute('aria-busy');render()}).catch(function(){location.reload()})}})});
})();
